### ISSUE TITLE
url for Find() doesn't include class name

### ISSUE THREAD

**Issue by nickoneill** [kylemcc/parse#2]
Hello again!

I'm doing a Find on a custom class like this:

    treats := make([]Treat, 10)
    treatQ, err := parse.NewQuery(&treats)
    if err != nil {
	    panic(err)
    }
    treatQ.OrderBy("-createdAt")
    treatQ.Limit(20)

    err = treatQ.Find()

And I'm getting `requested resource was not found` back from parse. I dug around a bit and it looks like getClassName in types.go isn't returning anything and the url ends up like this without the class name:

    https://api.parse.com/1/classes?limit=20&order=-createdAt

I don't have a whole lot of Go experience so the reflect stuff is somewhat over my head to fix. It seems like the alternative querying method like in the readme generates custom class URLs OK, and the same method is used in the tests.

**Comment by kylemcc** [comment]
Hi there! Thanks for the bug report - definitely a good catch. The referenced commit should fix the problem. I've added some unit tests for this case. Sorry the innards of this library are a little hairy. Now that it's starting to take shape, I need to start cleaning things up. :) Let me know if you run into any more trouble.

**Comment by nickoneill** [comment]
Works great, thanks!
